# Generated by Django 3.2.12 on 2022-02-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(default='askandola07@gmail.com', max_length=100),
        ),
    ]
